export const TEAMS = [
  {
    id: "lal",
    name: "Los Angeles Lakers",
    abbr: "LAL",
    conference: "Oeste",
    wins: 47,
    losses: 35,
    color: "#552583",
    players: 17,
  },
  {
    id: "bos",
    name: "Boston Celtics",
    abbr: "BOS",
    conference: "Este",
    wins: 61,
    losses: 21,
    color: "#007A33",
    players: 16,
  },
  {
    id: "gsw",
    name: "Golden State Warriors",
    abbr: "GSW",
    conference: "Oeste",
    wins: 46,
    losses: 36,
    color: "#1D428A",
    players: 17,
  },
  {
    id: "mia",
    name: "Miami Heat",
    abbr: "MIA",
    conference: "Este",
    wins: 46,
    losses: 36,
    color: "#98002E",
    players: 15,
  },
  {
    id: "den",
    name: "Denver Nuggets",
    abbr: "DEN",
    conference: "Oeste",
    wins: 57,
    losses: 25,
    color: "#0E2240",
    players: 16,
  },
  {
    id: "mil",
    name: "Milwaukee Bucks",
    abbr: "MIL",
    conference: "Este",
    wins: 49,
    losses: 33,
    color: "#00471B",
    players: 17,
  },
  {
    id: "phx",
    name: "Phoenix Suns",
    abbr: "PHX",
    conference: "Oeste",
    wins: 49,
    losses: 33,
    color: "#E56020",
    players: 15,
  },
  {
    id: "nyk",
    name: "New York Knicks",
    abbr: "NYK",
    conference: "Este",
    wins: 50,
    losses: 32,
    color: "#F58426",
    players: 16,
  },
];

export const PLAYERS = [
  {
    id: 1,
    name: "LeBron James",
    team: "Los Angeles Lakers",
    positions: ["PF", "SF"],
    overall: 92,
    archetype: "PlaySlash Bully",
    height: "6'9\"",
    weight: "250 lbs",
    number: 23,
    image: "/basketball-player-portrait.png",
    attributes: {
      threePointShot: 76,
      drivingDunk: 85,
      passAccuracy: 90,
      perimeterDefense: 74,
      speed: 87,
      strength: 89,
    },
    badges: { gold: 12, silver: 4, bronze: 9, hallOfFame: 1, total: 26 },
  },
  {
    id: 2,
    name: "Stephen Curry",
    team: "Golden State Warriors",
    positions: ["PG"],
    overall: 95,
    archetype: "Sharpshooter",
    height: "6'2\"",
    weight: "185 lbs",
    number: 30,
    image: "/basketball-guard-portrait.png",
    attributes: {
      threePointShot: 99,
      drivingDunk: 60,
      passAccuracy: 88,
      perimeterDefense: 70,
      speed: 88,
      strength: 55,
    },
    badges: { gold: 15, silver: 6, bronze: 5, hallOfFame: 3, total: 29 },
  },
  {
    id: 3,
    name: "Nikola Jokic",
    team: "Denver Nuggets",
    positions: ["C"],
    overall: 98,
    archetype: "Playmaking Big",
    height: "6'11\"",
    weight: "284 lbs",
    number: 15,
    image: "/basketball-center-portrait.png",
    attributes: {
      threePointShot: 82,
      drivingDunk: 70,
      passAccuracy: 97,
      perimeterDefense: 68,
      speed: 68,
      strength: 90,
    },
    badges: { gold: 18, silver: 3, bronze: 4, hallOfFame: 5, total: 30 },
  },
  {
    id: 4,
    name: "Jayson Tatum",
    team: "Boston Celtics",
    positions: ["SF", "PF"],
    overall: 95,
    archetype: "Two-Way Wing",
    height: "6'8\"",
    weight: "210 lbs",
    number: 0,
    image: "/basketball-forward-portrait.png",
    attributes: {
      threePointShot: 88,
      drivingDunk: 89,
      passAccuracy: 80,
      perimeterDefense: 84,
      speed: 85,
      strength: 78,
    },
    badges: { gold: 14, silver: 5, bronze: 6, hallOfFame: 2, total: 27 },
  },
  {
    id: 5,
    name: "Giannis Antetokounmpo",
    team: "Milwaukee Bucks",
    positions: ["PF", "C"],
    overall: 97,
    archetype: "Point Forward",
    height: "6'11\"",
    weight: "243 lbs",
    number: 34,
    image: "/tall-basketball-player.png",
    attributes: {
      threePointShot: 68,
      drivingDunk: 98,
      passAccuracy: 82,
      perimeterDefense: 88,
      speed: 90,
      strength: 95,
    },
    badges: { gold: 16, silver: 4, bronze: 5, hallOfFame: 4, total: 29 },
  },
  {
    id: 6,
    name: "Devin Booker",
    team: "Phoenix Suns",
    positions: ["SG"],
    overall: 89,
    archetype: "Shot Creator",
    height: "6'5\"",
    weight: "206 lbs",
    number: 1,
    image: "/basketball-shooting-guard.png",
    attributes: {
      threePointShot: 87,
      drivingDunk: 78,
      passAccuracy: 83,
      perimeterDefense: 72,
      speed: 82,
      strength: 65,
    },
    badges: { gold: 10, silver: 7, bronze: 8, hallOfFame: 1, total: 26 },
  },
];
