import type { Player } from "../interfaces/player.interface";
import type { Team } from "../interfaces/team.response";

export const MOCK_PLAYERS: Player[] = [
  {
    id: "1",
    name: "LeBron James",
    slug: "lebron-james",
    overall: 97,
    img: "https://cdn.nba.com/headshots/nba/latest/1040x760/2544.png",
    url: "https://www.nba.com/player/2544",
    team: "Los Angeles Lakers",
    positions: ["SF", "PF"],
    height: "6'9\"",
    weight: "250 lbs",
    archetype: "Playmaking Forward",
    badges: {
      bronze: 4,
      silver: 6,
      gold: 8,
      legendary: 5,
      hallOfFame: 3,
      total: 26,
    },
  },
  {
    id: "2",
    name: "Stephen Curry",
    slug: "stephen-curry",
    overall: 96,
    img: "https://cdn.nba.com/headshots/nba/latest/1040x760/201939.png",
    url: "https://www.nba.com/player/201939",
    team: "Golden State Warriors",
    positions: ["PG"],
    height: "6'2\"",
    weight: "185 lbs",
    archetype: "Sharp Shooter",
    badges: {
      bronze: 3,
      silver: 5,
      gold: 7,
      legendary: 6,
      hallOfFame: 4,
      total: 25,
    },
  },
  {
    id: "3",
    name: "Giannis Antetokounmpo",
    slug: "giannis-antetokounmpo",
    overall: 97,
    img: "https://cdn.nba.com/headshots/nba/latest/1040x760/203507.png",
    url: "https://www.nba.com/player/203507",
    team: "Milwaukee Bucks",
    positions: ["PF", "C"],
    height: "6'11\"",
    weight: "242 lbs",
    archetype: "Two-Way Finisher",
    badges: {
      bronze: 5,
      silver: 7,
      gold: 9,
      legendary: 4,
      hallOfFame: 2,
      total: 27,
    },
  },
  {
    id: "4",
    name: "Kevin Durant",
    slug: "kevin-durant",
    overall: 96,
    img: "https://cdn.nba.com/headshots/nba/latest/1040x760/201142.png",
    url: "https://www.nba.com/player/201142",
    team: "Phoenix Suns",
    positions: ["SF", "PF"],
    height: "6'10\"",
    weight: "240 lbs",
    archetype: "Scoring Machine",
    badges: {
      bronze: 3,
      silver: 6,
      gold: 8,
      legendary: 5,
      hallOfFame: 3,
      total: 25,
    },
  },
  {
    id: "5",
    name: "Nikola Jokic",
    slug: "nikola-jokic",
    overall: 99,
    img: "https://cdn.nba.com/headshots/nba/latest/1040x760/203999.png",
    url: "https://www.nba.com/player/203999",
    team: "Denver Nuggets",
    positions: ["C"],
    height: "6'11\"",
    weight: "284 lbs",
    archetype: "Pass-First Big",
    badges: {
      bronze: 2,
      silver: 4,
      gold: 7,
      legendary: 7,
      hallOfFame: 5,
      total: 25,
    },
  },
  {
    id: "6",
    name: "Luka Doncic",
    slug: "luka-doncic",
    overall: 96,
    img: "https://cdn.nba.com/headshots/nba/latest/1040x760/1629029.png",
    url: "https://www.nba.com/player/1629029",
    team: "Los Angeles Lakers",
    positions: ["PG", "SG"],
    height: "6'7\"",
    weight: "230 lbs",
    archetype: "Playmaking Shot Creator",
    badges: {
      bronze: 4,
      silver: 5,
      gold: 7,
      legendary: 5,
      hallOfFame: 2,
      total: 23,
    },
  },
  {
    id: "7",
    name: "Joel Embiid",
    slug: "joel-embiid",
    overall: 95,
    img: "https://cdn.nba.com/headshots/nba/latest/1040x760/203954.png",
    url: "https://www.nba.com/player/203954",
    team: "Philadelphia 76ers",
    positions: ["C"],
    height: "7'0\"",
    weight: "280 lbs",
    archetype: "Interior Force",
    badges: {
      bronze: 3,
      silver: 5,
      gold: 8,
      legendary: 4,
      hallOfFame: 2,
      total: 22,
    },
  },
  {
    id: "8",
    name: "Jayson Tatum",
    slug: "jayson-tatum",
    overall: 93,
    img: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628369.png",
    url: "https://www.nba.com/player/1628369",
    team: "Boston Celtics",
    positions: ["SF", "PF"],
    height: "6'8\"",
    weight: "210 lbs",
    archetype: "Versatile Scorer",
    badges: {
      bronze: 4,
      silver: 6,
      gold: 6,
      legendary: 3,
      hallOfFame: 1,
      total: 20,
    },
  },
  {
    id: "9",
    name: "Damian Lillard",
    slug: "damian-lillard",
    overall: 94,
    img: "https://cdn.nba.com/headshots/nba/latest/1040x760/203081.png",
    url: "https://www.nba.com/player/203081",
    team: "Milwaukee Bucks",
    positions: ["PG"],
    height: "6'2\"",
    weight: "195 lbs",
    archetype: "Scoring PG",
    badges: {
      bronze: 3,
      silver: 5,
      gold: 7,
      legendary: 4,
      hallOfFame: 2,
      total: 21,
    },
  },
  {
    id: "10",
    name: "Anthony Davis",
    slug: "anthony-davis",
    overall: 94,
    img: "https://cdn.nba.com/headshots/nba/latest/1040x760/203076.png",
    url: "https://www.nba.com/player/203076",
    team: "Los Angeles Lakers",
    positions: ["PF", "C"],
    height: "6'10\"",
    weight: "253 lbs",
    archetype: "Defensive Anchor",
    badges: {
      bronze: 4,
      silver: 6,
      gold: 7,
      legendary: 3,
      hallOfFame: 1,
      total: 21,
    },
  },
];

export const MOCK_TEAMS: Team[] = [
  {
    id: "1",
    name: "Celtics",
    city: "Boston",
    abbreviation: "BOS",
    slug: "boston-celtics",
    division: "Atlantic",
    overall: 96,
    logo: "",
    url: "https://www.nba.com/celtics/",
    arena: "TD Garden",
    founded: 1946,
    championships: 18,
    record: { wins: 64, losses: 18 },
    colors: {
      primary: "oklch(0.55 0.15 150)",
      secondary: "oklch(0.85 0.06 90)",
    },
  },
  {
    id: "2",
    name: "Nuggets",
    city: "Denver",
    abbreviation: "DEN",
    slug: "denver-nuggets",
    division: "Northwest",
    overall: 94,
    logo: "",
    url: "https://www.nba.com/nuggets/",
    arena: "Ball Arena",
    founded: 1967,
    championships: 1,
    record: { wins: 57, losses: 25 },
    colors: {
      primary: "oklch(0.45 0.12 250)",
      secondary: "oklch(0.78 0.16 75)",
    },
  },
  {
    id: "3",
    name: "Thunder",
    city: "Oklahoma City",
    abbreviation: "OKC",
    slug: "oklahoma-city-thunder",
    division: "Northwest",
    overall: 95,
    logo: "",
    url: "https://www.nba.com/thunder/",
    arena: "Paycom Center",
    founded: 1967,
    championships: 1,
    record: { wins: 68, losses: 14 },
    colors: {
      primary: "oklch(0.6 0.16 240)",
      secondary: "oklch(0.68 0.18 35)",
    },
  },
  {
    id: "4",
    name: "Lakers",
    city: "Los Angeles",
    abbreviation: "LAL",
    slug: "los-angeles-lakers",
    division: "Pacific",
    overall: 91,
    logo: "",
    url: "https://www.nba.com/lakers/",
    arena: "Crypto.com Arena",
    founded: 1947,
    championships: 17,
    record: { wins: 50, losses: 32 },
    colors: {
      primary: "oklch(0.55 0.18 300)",
      secondary: "oklch(0.82 0.16 85)",
    },
  },
  {
    id: "5",
    name: "Warriors",
    city: "Golden State",
    abbreviation: "GSW",
    slug: "golden-state-warriors",
    division: "Pacific",
    overall: 90,
    logo: "",
    url: "https://www.nba.com/warriors/",
    arena: "Chase Center",
    founded: 1946,
    championships: 7,
    record: { wins: 48, losses: 34 },
    colors: { primary: "oklch(0.5 0.14 255)", secondary: "oklch(0.8 0.16 80)" },
  },
  {
    id: "6",
    name: "Bucks",
    city: "Milwaukee",
    abbreviation: "MIL",
    slug: "milwaukee-bucks",
    division: "Central",
    overall: 92,
    logo: "",
    url: "https://www.nba.com/bucks/",
    arena: "Fiserv Forum",
    founded: 1968,
    championships: 2,
    record: { wins: 49, losses: 33 },
    colors: {
      primary: "oklch(0.45 0.08 155)",
      secondary: "oklch(0.9 0.03 90)",
    },
  },
  {
    id: "7",
    name: "Knicks",
    city: "New York",
    abbreviation: "NYK",
    slug: "new-york-knicks",
    division: "Atlantic",
    overall: 93,
    logo: "",
    url: "https://www.nba.com/knicks/",
    arena: "Madison Square Garden",
    founded: 1946,
    championships: 2,
    record: { wins: 51, losses: 31 },
    colors: {
      primary: "oklch(0.55 0.16 250)",
      secondary: "oklch(0.68 0.18 45)",
    },
  },
  {
    id: "8",
    name: "Timberwolves",
    city: "Minnesota",
    abbreviation: "MIN",
    slug: "minnesota-timberwolves",
    division: "Northwest",
    overall: 91,
    logo: "",
    url: "https://www.nba.com/timberwolves/",
    arena: "Target Center",
    founded: 1989,
    championships: 0,
    record: { wins: 49, losses: 33 },
    colors: {
      primary: "oklch(0.4 0.1 255)",
      secondary: "oklch(0.65 0.14 165)",
    },
  },
  {
    id: "9",
    name: "Mavericks",
    city: "Dallas",
    abbreviation: "DAL",
    slug: "dallas-mavericks",
    division: "Southwest",
    overall: 89,
    logo: "",
    url: "https://www.nba.com/mavericks/",
    arena: "American Airlines Center",
    founded: 1980,
    championships: 1,
    record: { wins: 39, losses: 43 },
    colors: {
      primary: "oklch(0.55 0.15 250)",
      secondary: "oklch(0.35 0.03 250)",
    },
  },
  {
    id: "10",
    name: "Heat",
    city: "Miami",
    abbreviation: "MIA",
    slug: "miami-heat",
    division: "Southeast",
    overall: 88,
    logo: "",
    url: "https://www.nba.com/heat/",
    arena: "Kaseya Center",
    founded: 1988,
    championships: 3,
    record: { wins: 37, losses: 45 },
    colors: { primary: "oklch(0.5 0.2 20)", secondary: "oklch(0.72 0.18 45)" },
  },
  {
    id: "11",
    name: "Cavaliers",
    city: "Cleveland",
    abbreviation: "CLE",
    slug: "cleveland-cavaliers",
    division: "Central",
    overall: 94,
    logo: "",
    url: "https://www.nba.com/cavaliers/",
    arena: "Rocket Mortgage FieldHouse",
    founded: 1970,
    championships: 1,
    record: { wins: 64, losses: 18 },
    colors: { primary: "oklch(0.4 0.12 20)", secondary: "oklch(0.78 0.14 85)" },
  },
  {
    id: "12",
    name: "Suns",
    city: "Phoenix",
    abbreviation: "PHX",
    slug: "phoenix-suns",
    division: "Pacific",
    overall: 87,
    logo: "",
    url: "https://www.nba.com/suns/",
    arena: "Footprint Center",
    founded: 1968,
    championships: 0,
    record: { wins: 36, losses: 46 },
    colors: {
      primary: "oklch(0.5 0.18 300)",
      secondary: "oklch(0.68 0.18 40)",
    },
  },
];
