import type { Player } from "../interfaces/player.interface";

export const MOCK_PLAYERS: Player[] = [
  {
    id: "1",
    name: "LeBron James",
    slug: "lebron-james",
    overall: 97,
    img: "https://cdn.nba.com/headshots/nba/latest/1040x760/2544.png",
    url: "https://www.nba.com/player/2544",
    team: "Los Angeles Lakers",
    positions: ["SF", "PF"],
    height: "6'9\"",
    weight: "250 lbs",
    archetype: "Playmaking Forward",
    badges: {
      bronze: 4,
      silver: 6,
      gold: 8,
      legendary: 5,
      hallOfFame: 3,
      total: 26,
    },
  },
  {
    id: "2",
    name: "Stephen Curry",
    slug: "stephen-curry",
    overall: 96,
    img: "https://cdn.nba.com/headshots/nba/latest/1040x760/201939.png",
    url: "https://www.nba.com/player/201939",
    team: "Golden State Warriors",
    positions: ["PG"],
    height: "6'2\"",
    weight: "185 lbs",
    archetype: "Sharp Shooter",
    badges: {
      bronze: 3,
      silver: 5,
      gold: 7,
      legendary: 6,
      hallOfFame: 4,
      total: 25,
    },
  },
  {
    id: "3",
    name: "Giannis Antetokounmpo",
    slug: "giannis-antetokounmpo",
    overall: 97,
    img: "https://cdn.nba.com/headshots/nba/latest/1040x760/203507.png",
    url: "https://www.nba.com/player/203507",
    team: "Milwaukee Bucks",
    positions: ["PF", "C"],
    height: "6'11\"",
    weight: "242 lbs",
    archetype: "Two-Way Finisher",
    badges: {
      bronze: 5,
      silver: 7,
      gold: 9,
      legendary: 4,
      hallOfFame: 2,
      total: 27,
    },
  },
  {
    id: "4",
    name: "Kevin Durant",
    slug: "kevin-durant",
    overall: 96,
    img: "https://cdn.nba.com/headshots/nba/latest/1040x760/201142.png",
    url: "https://www.nba.com/player/201142",
    team: "Phoenix Suns",
    positions: ["SF", "PF"],
    height: "6'10\"",
    weight: "240 lbs",
    archetype: "Scoring Machine",
    badges: {
      bronze: 3,
      silver: 6,
      gold: 8,
      legendary: 5,
      hallOfFame: 3,
      total: 25,
    },
  },
  {
    id: "5",
    name: "Nikola Jokic",
    slug: "nikola-jokic",
    overall: 99,
    img: "https://cdn.nba.com/headshots/nba/latest/1040x760/203999.png",
    url: "https://www.nba.com/player/203999",
    team: "Denver Nuggets",
    positions: ["C"],
    height: "6'11\"",
    weight: "284 lbs",
    archetype: "Pass-First Big",
    badges: {
      bronze: 2,
      silver: 4,
      gold: 7,
      legendary: 7,
      hallOfFame: 5,
      total: 25,
    },
  },
  {
    id: "6",
    name: "Luka Doncic",
    slug: "luka-doncic",
    overall: 96,
    img: "https://cdn.nba.com/headshots/nba/latest/1040x760/1629029.png",
    url: "https://www.nba.com/player/1629029",
    team: "Los Angeles Lakers",
    positions: ["PG", "SG"],
    height: "6'7\"",
    weight: "230 lbs",
    archetype: "Playmaking Shot Creator",
    badges: {
      bronze: 4,
      silver: 5,
      gold: 7,
      legendary: 5,
      hallOfFame: 2,
      total: 23,
    },
  },
  {
    id: "7",
    name: "Joel Embiid",
    slug: "joel-embiid",
    overall: 95,
    img: "https://cdn.nba.com/headshots/nba/latest/1040x760/203954.png",
    url: "https://www.nba.com/player/203954",
    team: "Philadelphia 76ers",
    positions: ["C"],
    height: "7'0\"",
    weight: "280 lbs",
    archetype: "Interior Force",
    badges: {
      bronze: 3,
      silver: 5,
      gold: 8,
      legendary: 4,
      hallOfFame: 2,
      total: 22,
    },
  },
  {
    id: "8",
    name: "Jayson Tatum",
    slug: "jayson-tatum",
    overall: 93,
    img: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628369.png",
    url: "https://www.nba.com/player/1628369",
    team: "Boston Celtics",
    positions: ["SF", "PF"],
    height: "6'8\"",
    weight: "210 lbs",
    archetype: "Versatile Scorer",
    badges: {
      bronze: 4,
      silver: 6,
      gold: 6,
      legendary: 3,
      hallOfFame: 1,
      total: 20,
    },
  },
  {
    id: "9",
    name: "Damian Lillard",
    slug: "damian-lillard",
    overall: 94,
    img: "https://cdn.nba.com/headshots/nba/latest/1040x760/203081.png",
    url: "https://www.nba.com/player/203081",
    team: "Milwaukee Bucks",
    positions: ["PG"],
    height: "6'2\"",
    weight: "195 lbs",
    archetype: "Scoring PG",
    badges: {
      bronze: 3,
      silver: 5,
      gold: 7,
      legendary: 4,
      hallOfFame: 2,
      total: 21,
    },
  },
  {
    id: "10",
    name: "Anthony Davis",
    slug: "anthony-davis",
    overall: 94,
    img: "https://cdn.nba.com/headshots/nba/latest/1040x760/203076.png",
    url: "https://www.nba.com/player/203076",
    team: "Los Angeles Lakers",
    positions: ["PF", "C"],
    height: "6'10\"",
    weight: "253 lbs",
    archetype: "Defensive Anchor",
    badges: {
      bronze: 4,
      silver: 6,
      gold: 7,
      legendary: 3,
      hallOfFame: 1,
      total: 21,
    },
  },
];
